ctf2: add varint test trace
eclipse-tracecompass/tracecompass-test-traces pull request #8
Opened 2024-05-09 13:53 UTC by vladarama

Adding a ctf2 varint trace to test the upcoming support of varints in TC. 

This trace has been taken from the ctf2 test folder of [yactfr] which has a proprietary `.streams` format which contains the metadata and shows the expected output of decoding such a trace.  This `.streams` file was then fed into a [python script] to convert it into an actual ctf2 trace with a `metadata` and a `stream` file. 

Please note that this is a data test trace, therefore it does not contain non-data features
such as attributes or a preferred display integer base.

Signed-off-by: Vlad Arama <vlad.arama@ericsson.com>

[yactfr]: https://github.com/eepp/yactfr/blob/master/tests/tests-iter-data/ctf-2/pass-vl-ints.streams
[python script]: https://github.com/eepp/yactfr/blob/master/tests/common/yactfrutils.py

2024-05-09 14:04 UTC, MatthewKhouzam requested changes
Looks good, you need to declare the trace in CtfTestTrace.java

2024-05-09 14:53 UTC, PatrickTasse approved these changes, later dismissed

2024-05-09 16:02 UTC, vladarama reviewed
Should be good to go now 👍

2024-05-10 17:31 UTC, PatrickTasse approved these changes, later dismissed

2024-05-13 15:35 UTC, PatrickTasse approved these changes

2024-05-13 17:42 UTC, MatthewKhouzam approved these changes

2024-05-13 17:44 UTC, merged